alias ll='ls -lah'
alias la='ls -A'
alias c='clear'
alias vim='nvim'
alias rel="source ~/.zshrc"
alias archit='ssh xerneas@archy'
alias ta='tmux attach'
alias tmks='tmux kill-server'
alias tm='tmux'
alias tmkss='tmux kill-session -t'
# alias head='5.78.108.179'
alias jarch='ssh -L 8888:localhost:8888 xerneas@archy'
alias nuke='ssh software@100.64.0.58'
alias c='clear'
alias setup='npm run setup'
alias bake='ssh xerneas@cake'
alias l='eza -lah --icons'
alias win='ssh senth@brick'
alias wsl='ssh -t senth@aakashdesktop "wsl.exe"'
alias cd='z'
alias head='ssh root@headscale'
alias ts='tailscale status'
alias ff='fastfetch'
alias ze='nvim ~/.zshrc'
alias za='nvim ~/.config/zsh/alias.zsh'
alias n='nvim'
# ss() {
#   local file
#   file=$(fzf --preview='bat --color=always {}') || return
#   nvim "$file"
# }
alias ss='source .venv/bin/activate'
alias up='uv pip install'
alias bum='ssh xerneas@jetson'
alias desk='ssh software@100.64.0.25'
alias wm='ssh admin@wimspi'
alias blaze='ssh xerneas@blazepi'
alias bit='ssh software@100.64.0.58'

alias tr='tailscale switch robotics-infra'
alias tx='tailscale switch xerneas'
alias tp='tailscale switch --list'
alias butata='ssh software@100.64.0.58'
alias pls='sudo $(fc -ln -1)'
alias btop='~/Documents/Coding/btop-macos-gpu/bin/btop'
alias fah='sudo spank --min-amplitude 0.15 --custom ~/Downloads/fah'
